#!/bin/sh
# postrm script for rdma
#

set -e

case "$1" in
    purge|remove|failed-upgrade|abort-install|abort-upgrade|disappear)
        systemctl daemon-reload >/dev/null 2>&1 || true
    ;;

    upgrade)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
