#!/bin/sh
# postinst script for rdma
#

set -e

case "$1" in
    configure)
        systemctl daemon-reload >/dev/null 2>&1 || true
        systemctl enable rdma >/dev/null  2>&1 || true
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
